name: Feature Request
labels: ["enhancement"]
description: Suggest a feature or improvement idea for the app
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Suggest a feature or improvement idea for the app
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: App version
      description: What version of the app this request is for?
      options:
        - v1
        - v2
      default: 1
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        
        #### Notes
        Join our Patreon community to increase the priority of all your requests!
        Patreon: [https://patreon.com/sigma_file_manager](https://patreon.com/sigma_file_manager)
