name: Problem Report
description: Create a problem report to help improve the app
labels: [bug]
body:
- type: textarea
  attributes:
    label: Problem description
    description: A clear & concise description of what you're experiencing.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Specify steps to reproduce the behavior.
    value: |
      1. 
  validations:
    required: true
    
- type: input
  id: os
  attributes:
    label: Operating system
    description: "Specify the operating system you are running the app on"
    placeholder: "For example: Windows 11, MacOS Ventura, etc."
  validations:
    required: true
    
- type: dropdown
  id: version
  attributes:
    label: App version
    description: What version of the app this request is for?
    options:
      - v1
      - v2
    default: 1
  validations:
    required: true
